### ISSUE TITLE
What "super_general=True" argument does exactly in process_an_example?

### ISSUE THREAD

**Issue by zas97** [connorcoley/retrosim#4]
What "super_general=True" argument does exactly in the file retrosim/utils/generate_retro_templates.py in the function process_an_example.

**Comment by connorcoley** [comment]
The retrosynthetic templates applied by retrosim are meant to minimally
define the reaction center, as there are other similarity-based checks for
whether the template is appropriate to apply (rather than an extended
subgraph containing neighbors of the reaction center). super_general makes
it so that extracted templates do not contain any context beyond what is
necessary to reconstruct valid reactant smiles given a product. If you're
interested in more general-purpose retrosynthetic templates where some
degree of structural context is contained, I'd steer you toward
https://github.com/connorcoley/rdchiral/blob/master/templates/template_extractor.py
 & https://pubs.acs.org/doi/abs/10.1021/acs.jcim.9b00286

**Comment by zas97** [comment]
Thank you!
